SET(UTIL_SAMPLE_FILES
Util/Bitmap.cpp
Util/Bitmap.h
Util/drvapi_error_string.h
Util/helper_cuda.h
Util/helper_cuda_drvapi.h
Util/helper_cuda_gl.h
Util/helper_string.h
Util/NvFBCLibrary.h
Util/NvIFRLibrary.h
Util/ReadMe.txt
Util/Timer.cpp
Util/Timer.h
Util/Util.h
Util/Util.vcproj
Util/Util.vcxproj
)